### ISSUE TITLE
Filter Example mentioned in the Docs does not work?

### ISSUE THREAD

**Issue by colonyshipforsale** [alephdata/followthemoney#407]
after discussion here https://github.com/alephdata/aleph/issues/1764 reopening it in the correct place:

It seems **Filtering source data** as described in the docs do not work? See @ https://docs.alephdata.org/developers/mappings

Aleph generated **all 653** entities present in the CSV instead of the filtered (conservative & not male) **67 entities**.

- **I am grateful for any hints, maybe i am doing something wrong? CSV and YML are according to the docs.**
- **I want to use mixed entities in a CSV and only load specific rows ... i suppose the filter would let me do that, no?**
- acc. to @pudo this might be relevant (Ref: https://github.com/alephdata/followthemoney/blob/master/followthemoney/mapping/source.py#L22 )

To reproduce:

> I am using the UI and Version 3.10.0 (docker)
> 
> I uploaded the CSV and **before generating the entities** i loaded **filters.yml** (see below)
> 

**source data**

> http://bit.ly/uk-mps-csv

**filters.yml**

> ```
> gb_parliament_57:
>   queries:
>   - csv_url: http://bit.ly/uk-mps-csv
>     filters:
>       group: "Conservative"
>     filters_not:
>       gender: "male" 
>     entities:
>       member:
>         schema: Person
>         keys:
>         - id
>         properties:
>           name:
>             column: name
> ```

**Comment by colonyshipforsale** [comment]
I got around to learn a bit to use the FTM cli and wanted to find out if the filter behaviour between FTM-cli and UI is equivalent?

So i prepared 2 CSV's and 2 Filter YML (see further below) ...
- once streamed via FTM-cli and
- once via UI (selecting CSV + YML + clicking generate entities etc.)

Expected behaviour was that UI and FTM-cli processing would create the same entities?

I attached some screenshots, in the end at least to my limited knowledge, the FTM-cli processing result (see below right column) differs from the UI processing result (see left column).

While i could simplify the test case by using just filter (and ommit "filters_not") they already behave differently .. so there you go :) some more info, let me know if I did something totally wrong ?


![Filters_UI_vs_FTM_company](https://user-images.githubusercontent.com/73785468/117569921-3d1a1780-b0c8-11eb-8294-b1f22e7f5801.jpg)
![Filters_UI_vs_FTM_otherlinks](https://user-images.githubusercontent.com/73785468/117569923-3ee3db00-b0c8-11eb-96aa-b84cb70bbf95.jpg)
![Filters_UI_vs_FTM_publicbodies](https://user-images.githubusercontent.com/73785468/117569924-3f7c7180-b0c8-11eb-8c0c-1d3f6ad87a59.jpg)

CSV
[Company.csv](https://github.com/alephdata/followthemoney/files/6447352/Company.csv)
[CompanyPublicBody.csv](https://github.com/alephdata/followthemoney/files/6447353/CompanyPublicBody.csv)


YML - Company.csv
```

218.a281c881ec83dd5172babbcee00b8a552ecdeded:
  label: Company.csv
  info_url: http://aleph:8080/entities/218.a281c881ec83dd5172babbcee00b8a552ecdeded
  query:
    filters:
      Thing_1_Type: "FilterPropertyCompany"
    entities:
      Company:
        schema: Company
        keys:
          - Thing_1_UID
        properties:
          name:
            column: Thing_1_Name
```

YML - CompanyPublicBody.csv

```
218.a281c881ec83dd5172babbcee00b8a552ecdeded:
  label: CompanyPublicBody.csv
  info_url: http://aleph:8080/entities/218.a281c881ec83dd5172babbcee00b8a552ecdeded
  query:
    filters:
      Thing_1_Type: "FilterPropertyCompany"
    filters_not:
      Thing_2_Type: "FilterPropertyPublicBody" 
    entities:
      Company:
        schema: Company
        keys:
          - Thing_1_UID
        properties:
          name:
            column: Thing_1_Name
      PublicBody:
        schema: PublicBody
        keys:
          - Thing_2_UID
        properties:
          name:
            column: Thing_2_Name
      UnknownLink:
        schema: UnknownLink
        keys:
          - Thing_1_UID
          - Thing_2_UID
        properties:
          role:
            column: Interval_Verbose
          object:
            entity: Company
            required: true
          subject:
            entity: PublicBody
            required: true
          summary:
            column: Interval_Summary
          description:
            column: Interval_Type
        key_literal: UnknownLink
```
