### ISSUE TITLE
Add new entity type Debt.

### ISSUE THREAD

**Issue by dchaplinsky** [alephdata/followthemoney#58]
Intervals we have currently doesn't fit debtor/creditor relationship.

I'm attaching proposed schema

```yaml
Debt:
  label: "Debt"
  plural: "Debts"
  description: "A monetary debt between two parties."
  extends: 
    - Interval
    - Value
  matchable: false
  featured:
    - debtor
    - creditor
    - date
    - amount
  edge:
    source: debtor
    target: creditor
  properties:
    debtor:
      label: "Debtor"
      reverse:
        name: debtDebtor
        label: "Debts"
      type: entity
      range: LegalEntity
    creditor:
      label: "creditor"
      reverse:
        name: debtCreditor
        label: "Credits"
      type: entity
      range: LegalEntity
```
