### ISSUE TITLE
Add literal component to key.

### ISSUE THREAD

**Issue by pudo** [alephdata/followthemoney#8]
We currently have a few conditions where the fields in the source data are not sufficient to generate a unique ID for certain entities (especially those which define a relationship between two other entities, e.g. a company and it's director). We should therefore add a literal extra component to the key like this:

```
ownership:
  schema: Ownership
  keys:
    - director_name
    - company_name
  key_literal:
    - "Ownership"
directorship:
  schema: Directorship
  keys:
    - director_name
    - company_name
  key_literal:
    - "Directorship"
```
